default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default
  database: thermostats_statistics_dev

test:
  <<: *default
  database: thermostats_statistics_test

production:
  <<: *default
  database: thermostats_statistics_prod
